morning_train:
  from: "WIN"          # Winchester
  to: "WAT"            # Waterloo
  departure: "0725"
  days:                # Days to monitor (omit for every day)
    - wednesday

evening_train:
  from: "WAT"
  to: "WIN"
  departure: "1635"
  days:
    - wednesday
